#!/usr/bin/env bash
# Export Terraform outputs as shell env vars for local seeding against AWS.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="${ROOT}/terraform"

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform is required. Install: https://developer.hashicorp.com/terraform/install"
  exit 1
fi

cd "$TF_DIR"

if [[ ! -f terraform.tfstate && ! -d .terraform ]]; then
  echo "Run 'npm run infra:apply' first."
  exit 1
fi

REGION=$(terraform output -raw aws_region)
KEY=$(terraform output -raw iam_access_key_id)
SECRET=$(terraform output -raw iam_secret_access_key)

export USE_LOCAL_STORE=false
export AWS_REGION="$REGION"
export AWS_ACCESS_KEY_ID="$KEY"
export AWS_SECRET_ACCESS_KEY="$SECRET"
export DYNAMODB_PRODUCTS_TABLE=$(terraform output -raw dynamodb_table_products)
export DYNAMODB_OWNERSHIP_TABLE=$(terraform output -raw dynamodb_table_ownership_events)
export DYNAMODB_RECALLS_TABLE=$(terraform output -raw dynamodb_table_recall_events)
export DYNAMODB_STATUS_TABLE=$(terraform output -raw dynamodb_table_user_recall_status)

S3_BUCKET=$(terraform output -raw s3_receipts_bucket 2>/dev/null || true)
if [[ -n "$S3_BUCKET" ]]; then
  export S3_RECEIPTS_BUCKET="$S3_BUCKET"
fi

echo "AWS env loaded from Terraform outputs (region=$AWS_REGION)."
echo "Tables: $DYNAMODB_PRODUCTS_TABLE, $DYNAMODB_OWNERSHIP_TABLE, ..."

if [[ "${1:-}" == "--write" ]]; then
  OUT="${ROOT}/.env.aws"
  cat > "$OUT" <<EOF
# Generated by scripts/terraform-env.sh — do not commit
USE_LOCAL_STORE=false
AWS_REGION=$AWS_REGION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
DYNAMODB_PRODUCTS_TABLE=$DYNAMODB_PRODUCTS_TABLE
DYNAMODB_OWNERSHIP_TABLE=$DYNAMODB_OWNERSHIP_TABLE
DYNAMODB_RECALLS_TABLE=$DYNAMODB_RECALLS_TABLE
DYNAMODB_STATUS_TABLE=$DYNAMODB_STATUS_TABLE
S3_RECEIPTS_BUCKET=${S3_RECEIPTS_BUCKET:-}
EOF
  echo "Wrote $OUT"
fi
